services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app_laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - todo_network

  nginx:
    image: nginx:1.19-alpine
    container_name: todo_app_nginx
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_network

  db:
    image: mysql:8.0
    container_name: todo_app_db
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - ./data-db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - todo_network

  redis:
    image: redis:6.2-alpine
    container_name: todo_app_redis
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge